export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const UPDATE_PRODUCT_DESCRIPTION='UPDATE_PRODUCT_DESCRIPTION';
export const ADD_NEW_PRODUCT='ADD_NEW_PRODUCT';
export const DELETE_PRODUCT='DELETE_PRODUCT';
export const SORT_PRODUCTS='SORT_PRODUCTS';
export const INCREASE_QUANTITY='INCREASE_QUANTITY';
export const DECREASE_QUANTITY='DECREASE_QUANTITY';